# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  database: vtwit_dev
  <<: *defaults
  <<: *defaults_developmet

test:
  database: vtwit_dev_test
  <<: *defaults
  <<: *defaults_developmet

production:
  database: vtwit_dev_production
  <<: *defaults
  <<: *defaults_developmet

